// customerId
// customerFirstName
// customerLastName
// customerEmail
// customerPhone
// customerCountry
// customerState
// customerCity
// customerZip
// customerAddress
// customerStatus
// customerCreatedDate
// customerUpdatedDate
